version: '3.8'

services:
  npc-backend:
    build: .
    container_name: unity_npc_python_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always